### ISSUE TITLE
Is the "lifecycle" state machine correct?

### ISSUE THREAD

**Issue by NorbertSandor** [arkivanov/Decompose#147]
This doesn't seem to be correct: https://github.com/arkivanov/Decompose/blob/master/docs/media/LifecycleStates.png

These:
```
STARTED -- onResume --> RESUMED
RESUMED -- onPause --> STARTED
```

**Comment by arkivanov** [comment]
This is by design. The lifecycle has 5 possible states - INITIALIZED, CREATED, STARTED, RESUMED and DESTROYED. So when the lifecycle gets paused, it goes from RESUMED state back to STARTED state.

This reflects the Android lifecycle:

- https://developer.android.com/codelabs/basic-android-kotlin-training-activity-lifecycle#3
- https://developer.android.com/reference/androidx/lifecycle/Lifecycle.State
