### ISSUE TITLE
Unexpected side effect from Children animation

### ISSUE THREAD

**Issue by VladislavSumin** [arkivanov/Decompose#186]
When we navigate, for example with `replaceCurrent` with existing animation instanceKeeper && lifecycle of old screen destroying immediately.
`decompose-1.0.0-alpha-03-sources.jar!/commonMain/com/arkivanov/decompose/router/stack/StackControllerImpl.kt:49`

Expecting behavior: instanceKeeper && lifecycle are destroyed AFTER animation complete.

UPD: it is also quite unexpected that InstanceKeeper does not throw an exception when trying to use it after onDestroy

**Comment by arkivanov** [comment]
Hello. This is actually by design. The `decompose` core module does not know anything about animations. The navigation is performed synchronously from one screen to another. Once the navigation method returns, the components are already switched, and their lifecycles are switched as well. However this should cause any glitches. The destroyed component should hold the last state and the animation should be performed just fine. You can check the [TodoApp](https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp) sample - the Details screen is immediately destroyed when closed, and the animation continues just fine.

**Comment by arkivanov** [comment]
Re: it is also quite unexpected that InstanceKeeper does not throw an exception when trying to use it after onDestroy

This is a good point! I have filed https://github.com/arkivanov/Essenty/issues/69 for this.

**Comment by VladislavSumin** [comment]
Thanks for the answer,

Yes, you are right, I used InstanceKeeper not quite for its intended purpose. I kept the ViewModel instance in it. Now I understand what was my mistake and I will fix it.

ps I created a pull request where I added a check `isDestroyed` for InstenceKeeper
