### ISSUE TITLE
Running app-darwin-compose sample on real iOS device

### ISSUE THREAD

**Issue by serhiynovos** [arkivanov/Decompose#189]
Can you please provide gradle configuration for running sample app on real iOS device

**Comment by arkivanov** [comment]
Thanks for pointing it out! I will be able to do it only in the middle of September, because i don't have my iOS device handy. I will appreciate it if someone would like to contribute. I think changes should be done in the `compose-darwin` branch, in the following file. 

https://github.com/arkivanov/Decompose/blob/d29e1229193c09df7bd16003e2a88fb2af1956e6/sample/app-darwin-compose/build.gradle.kts#L16.

**Comment by arkivanov** [comment]
Closed via #199
