### ISSUE TITLE
stack animation break text color

### ISSUE THREAD

**Issue by b95505017** [arkivanov/Decompose#330]
[MyApplication.zip](https://github.com/arkivanov/Decompose/files/10821689/MyApplication.zip)

1. click `testA` button, you could see `test` button enable/disable correctly.
2. switch to another tab and switch back
3. click `testA` button again, text color of `test` button stick with same color (but button color change state correctly).
4. remove stack animation, text color change correctly.

**Comment by arkivanov** [comment]
Hello and thanks for reporting the issue with the reproducer! This appears to be a bug in Jetpack Compose, related to `movableContentOf`, similar to #326. I have filed https://issuetracker.google.com/issues/270656235. Let's keep this issue open for tracking purposes.

**Comment by b95505017** [comment]
@arkivanov Thanks! Did you find any workaround currently?

**Comment by arkivanov** [comment]
I didn't try yet. You can try downgrading Jetpack Compose below 1.3.1.

**Comment by b95505017** [comment]
@arkivanov Fortunately, I found that it works with downgrading to `1.4.0-beta01` and keep compiler and m3 with latest version.

**Comment by arkivanov** [comment]
Thanks for providing the workaround!

**Comment by b95505017** [comment]
Just wondering:
1. Which changes between beta01..beta02 break these things
2. Does official NavHost with animation would face this issue as well?
3. Any way to skip this kind of issue from Decompose side. (e.g. alternative API usage with `movableContentOf`)

**Comment by b95505017** [comment]
Not sure if there is anything could borrow from https://github.com/google/accompanist/tree/main/navigation-animation

**Comment by arkivanov** [comment]
1. Unfortunately, I don't know. The issue is also reproducible on Jetpack Compose 1.3.1.
2. The official navigation may work fine because it has a very limited support of animations.
3. This is tricky and not possible without breaking the API. `movableContentOf` appears to be pretty unstable, but it is used by Stack Animations in order to allow having different animations for different children/directions/etc. The should be possible to avoid `movableContentOf` for the simple variant of [stackAnimation](https://github.com/arkivanov/Decompose/blob/d708782e889771a5753be59134806d128acdcfe4/extensions-compose-jetpack/src/main/java/com/arkivanov/decompose/extensions/compose/jetpack/stack/animation/StackAnimation.kt#L42) function without `selector` argument. Though some minor changes to the API will be still required. For the variant with `selector` this is even more complicated.

For now I'm willing to wait for the fix and monitor how this will be doing in the future. The sibling issue #326 with scrolling in JetBrains Compose is already fixed (and perhaps released). Breaking the API is pretty undesirable, as `movableContentOf` allowed me to make the API simpler and concise.

**Comment by b95505017** [comment]
Sure. These are just my personal thoughts.

**Comment by arkivanov** [comment]
I will check accompanist animations, maybe we could derive something from there. Thanks for sharing.

**Comment by arkivanov** [comment]
It appears that accompanist uses `androidx.compose.animation`, which has a fixed set of possible transitions. For instance, here is [EnterTransition](https://developer.android.com/reference/kotlin/androidx/compose/animation/EnterTransition). It has fade, scale, slide and expand, and perhaps combinations. But it doesn't look possible to define custom transitions. In this case it's obvious that `movableContentOf` is not needed.

Stack Animation API in Decompose allows custom transitions. But anyway, I will think if there any ways to avoid `movableContentOf`.

**Comment by b95505017** [comment]
Looking forward to it!

**Comment by arkivanov** [comment]
I was able to fix the issue for some of the most often cases. However, the fix requires one breaking API change. I will think more about it, how this can be avoided or how to release the fix.

Here is the draft.

Add a new overload for `stackAnimation` function:

```kotlin 
// This API remains affected by `movableContentOf`
fun <C : Any, T : Any> stackAnimation(
    disableInputDuringAnimation: Boolean = true,
    selector: (child: Child.Created<C, T>, otherChild: Child.Created<C, T>, direction: Direction) -> StackAnimator?,
): StackAnimation<C, T>

// This is the new API, not affected by `movableContentOf`
fun <C : Any, T : Any> stackAnimation(
    disableInputDuringAnimation: Boolean = true,
    selector: (child: Child.Created<C, T>) -> StackAnimator?,
): StackAnimation<C, T>

// This API becomes not affected by `movableContentOf`
fun <C : Any, T : Any> stackAnimation(
    animator: StackAnimator = fade(),
    disableInputDuringAnimation: Boolean = true,
): StackAnimation<C, T>
```

Also add a new argument to `StackAnimator` (this is the breaking API change):

```kotlin
fun interface StackAnimator {

    @Composable
    operator fun invoke(
        direction: Direction,
        isInitial: Boolean, // <-- Add this argument - allows skipping the animation when the stack is initially appeared
        onFinished: () -> Unit,
        content: @Composable (Modifier) -> Unit,
    )
}
```

**Comment by arkivanov** [comment]
Maybe it worth releasing `v2.0.0` together with the API changes from #327?

**Comment by b95505017** [comment]
LGTM

**Comment by arkivanov** [comment]
The cause issue in Compose has just been marked as fixed. I think the fix should go in the next Compose release (22nd April).

**Comment by arkivanov** [comment]
The fix on the Decompose side will be released in the next major update, as described in https://github.com/arkivanov/Decompose/issues/330#issuecomment-1454792564.
