### ISSUE TITLE
Expected class 'ParcelableStub' has no actual declaration in module

### ISSUE THREAD

**Issue by jadhavd18** [arkivanov/Decompose#352]
Facing this issue while building my android project

> Task :decompose:compileDebugUnitTestKotlinAndroid FAILED
e: file:///Users/dhananjayjadhav/StudioProjects/KotlinMultiplatform/decompose/src/commonTest/kotlin/com/arkivanov/decompose/statekeeper/ParcelableStub.kt:5:14 Expected class 'ParcelableStub' has no actual declaration in module <decompose_debug> for JVM

> Task :decompose:compileReleaseUnitTestKotlinAndroid FAILED
e: file:///Users/dhananjayjadhav/StudioProjects/KotlinMultiplatform/decompose/src/commonTest/kotlin/com/arkivanov/decompose/statekeeper/ParcelableStub.kt:5:14 Expected class 'ParcelableStub' has no actual declaration in module <decompose_release> for JVM

**Comment by arkivanov** [comment]
Are you compiling Decompose?

**Comment by jadhavd18** [comment]
I am compiling my project which has this decompose added as local module as dependancy

**Comment by arkivanov** [comment]
Ok, I'm not sure why do you compile Decompose test sources. But that error might be because Decompose uses `kotlin.mpp.androidSourceSetLayoutVersion=2`.

See https://github.com/arkivanov/Decompose/blob/5e9d7de05b3c4d15a9036b72a99e5927683c5742/gradle.properties#L9

The mentioned class is here: https://github.com/arkivanov/Decompose/blob/master/decompose/src/androidUnitTest/kotlin/com/arkivanov/decompose/statekeeper/ParcelableStub.kt

Decompose builds fine on CI, there seems to be an error in your project's configs.

**Comment by arkivanov** [comment]
If you need to modify Decompose for your needs, then I recommend building and publishing it locally from sources. Just check out the repo, modify as needed, and run `publishToMavenLocal`. Then you can add it as a dependency to your project, just add `mavenLocal` to your repository list.

**Comment by jadhavd18** [comment]
Ohh okay thanks
