### ISSUE TITLE
Why we go to INITIALIZED state after onDestoy? Maybe DESTROYED?

### ISSUE THREAD

**Issue by DanilKolesGitHub** [arkivanov/Decompose#393]
https://github.com/arkivanov/Decompose/blob/a7b224a270a459124edb410ce14a44aad85798ee/decompose/src/commonMain/kotlin/com/arkivanov/decompose/lifecycle/MergedLifecycle.kt#L63

**Comment by arkivanov** [comment]
Maybe we could change that, I don't remember from the top of my head why exactly is it like this. But it shouldn't affect anything, since onDestroy is still should be called and the lifecycle should switch to DESTROYED state. Here is the test: https://github.com/arkivanov/Decompose/blob/a7b224a270a459124edb410ce14a44aad85798ee/decompose/src/commonTest/kotlin/com/arkivanov/decompose/lifecycle/MergedLifecycleTest.kt#L288

**Comment by arkivanov** [comment]
Do you have any issues?

**Comment by DanilKolesGitHub** [comment]
No, just a question. So that you remember if something goes wrong.
`INITIALIZED > DESTROYED`
So consecutive onDestroy calls from lifecycle 1 and lifecycle 2 will call `registry::onDestroy` twice.
But `registry.doOnDestroy` is triggered on the first onDestroy and unsubscribes from the second. Therefore, the test passes.

Thank you for your answer

**Comment by arkivanov** [comment]
Actually there is another bug! I have uploaded a fix with new tests. Thanks for raising!
