### ISSUE TITLE
Not able to access Children from decompose latest lib

### ISSUE THREAD

**Issue by anshulupadhyay03** [arkivanov/Decompose#416]
Hi, I have added the new library version(com.arkivanov.decompose:decompose:2.0.0-beta-01) to my kmm app. Everything works fine but I am not able to access the [Children](https://github.com/arkivanov/Decompose/blob/master/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/Children.kt) apis from the extensions(not working on both jetpack and JetBrains)

Here is the common build.gradle file: https://pastebin.com/dAGxaXbf 
and this is the dependencies file : https://pastebin.com/y9tLt1yY

**Comment by arkivanov** [comment]
Since you are targeting iOS, you should use the special version [2.0.0-compose-experimental-beta-01](https://github.com/arkivanov/Decompose/releases/tag/2.0.0-compose-experimental-beta-01). iOS is currently published from the `compose-experimental` branch, but I'm considering moving it to the main branch. See #74.

**Comment by arkivanov** [comment]
Closing this for now.
