### ISSUE TITLE
Child instance nullable

### ISSUE THREAD

**Issue by DatL4g** [arkivanov/Decompose#433]
Can we change the `instance` type from `out T : Any` to `out T : Any?` [here](https://github.com/arkivanov/Decompose/blob/master/decompose/src/commonMain/kotlin/com/arkivanov/decompose/Child.kt)?

I have the usecase for example that I have a TwoPane like implementation.
If something on the left site is clicked, then we can show details on the right side.
However if nothing is clicked (yet) then the right side is empty.

The child then should only render if one is present

I want to make it like this:

```kotlin
val child: Value<ChildSlot<Config, Component?>>

@Composable
fun Pane() {
	val state by child.subscribeAsState()

	state.child?.also { (config, instance) ->
		instance?.render()
	}
}
```

**Comment by malliaridis** [comment]
If I get you right what you want to achieve is already supported, you simply have to remove the `?` from `state.child?`:

```kotlin
val child: Value<ChildSlot<Config, Component>>

@Composable
fun Pane() {
    val state by child.subscribeAsState()

    state.child.also { child -> 
        child?.instance?.render()
    }
    
    // or simply
    state.child?.instance?.render()
}
```
Please also note that the component in `ChildSlot` does not have to be optional, because if correctly implemented, the child component in `ChildSlot` should only be created if the details should be shown.

You can also deconstruct your child only if the child is available, like:
```kotlin
state.child.also { child -> 
    val (config, instance) = child ?: return@also
    instance.render()
}
```

I don't think that making `Any` optional as you requested would be a good idea, because it would introduce unnecessary breaking changes.

If you also show us how you instantiate and update / fill your state, we may provide additional support. :)

**Comment by DatL4g** [comment]
https://github.com/DATL4G/eSports-Prodigy/blob/master/app/src/commonMain/kotlin/dev/datlag/esports/prodigy/ui/screen/home/counterstrike/CounterStrikeViewComponent.kt

Building the childSlot in line 47 always requires something to return, I just want to pass null in the when else statement

**Comment by arkivanov** [comment]
Having `ChildSlot<C : Any, T : Any?>` will always force checking the instance for null, it will be impossible to have guaranteed non-null instance. Having `ChildSlot<C, T>` would be ok in Kotlin, but there would be the same problem again in Swift, due to the way how generics are currently exported via Objective C. The current approach seems like a good trade-off.

What is the actual use case of having a slot child with a configuration but without a component instance? Regardless, if you really want it, you can define your children as follows.

```kotlin
private val _child = 
    childSlot<CounterStrikeConfig, Child>(
        source = navigation,
        initialConfiguration = {
            CounterStrikeConfig.Empty
        },
        handleBackButton = true
    ) { config, componentContext ->
        when (config) {
            is CounterStrikeConfig.Team -> Child.Team(TeamViewComponent(...))
            is CounterStrikeConfig.Empty -> Child.None
        }
    }

override val child: Value<ChildSlot<*, Child>> = _child

sealed class Child {
    class Team(val component: TeamViewComponent) : Child()
    object None : Child()
}
```

**Comment by arkivanov** [comment]
Please also mind that ChildSlot can be empty. E.g. you can omit the `initialConfiguration` argument and there will be no child. Then you can use `navigation.activate(...)` and `navigation.dismiss()` to show and hide the child.

```kotlin
private val _child = 
    childSlot<CounterStrikeConfig, Child>(
        source = navigation,
        handleBackButton = true
    ) { config, componentContext ->
        when (config) {
            is CounterStrikeConfig.Team -> Child.Team(TeamViewComponent(...))
        }
    }

override val child: Value<ChildSlot<*, Child>> = _child

sealed class Child {
    class Team(val component: TeamViewComponent) : Child()
}
```

Or even like this, if you have only one possible child.

```kotlin
private val _child = 
    childSlot<TeamConfig, TeamViewComponent>(
        source = navigation,
        handleBackButton = true
    ) { config, componentContext -> TeamViewComponent(...) }

override val child: Value<ChildSlot<*, TeamViewComponent>> = _child
```

**Comment by DatL4g** [comment]
Ohh I completely forgot about the `activate` and `dismiss` thing, even though I already use it for dialogs etc.
That's seems like the most viable solution in my case thanks.
