### ISSUE TITLE
Improve the documentation about the implementation

### ISSUE THREAD

**Issue by devjorgecastro** [arkivanov/Decompose#434]
I think the documentation about how to implement "Decompose" in a Compose Multiplatform project could be improved, I have followed the "Quick Start" and although I managed to get it to work in the Android project I couldn't get it to work with iOS.

perhaps a very simple example (Compose Multiplatform) that can serve as a template to create a project from scratch

**Comment by arkivanov** [comment]
Yes, this can be challenging. But I feel that this is due to the general steep learning curve with KMP? Assuming you have a project kick-started from e.g. [JetBrains/compose-multiplatform-template](https://github.com/JetBrains/compose-multiplatform-template), would the existing Decompose docs enough?

**Comment by malliaridis** [comment]
I think a dedicated version for iOS wouldn't be a bad idea. Especially the `iosApp` files (the Swift part) may be tricky to implement correctly for those that work only with Kotlin. But I am also not sure if this should be part of Decompose, as this affect more than Decompose (e.g. Compose, Cocoapods plugin and Essenty).

With that said, there is information spread across the documentation that could be placed at one place in form of a guide / step-by-step instructions. This would include the export of the library (found [here](https://arkivanov.github.io/Decompose/getting-started/installation/#exporting-decompose-to-ios-framework)) and the extension of the original dependencies with `-experimental` (found [here](https://arkivanov.github.io/Decompose/extensions/compose/#compose-for-ios-macos-and-web-canvas)).

From Compose site there are no additional steps necessary, as long as you follow the instructions described in their [template](https://github.com/JetBrains/compose-multiplatform-template).

I personally had an existing project and followed the steps below to add iOS support:
1. Copy the `iosApp` module from the Compose template into the project
2. Update your `gradle.properties` according to the Compose template
2. Copy the `cleanup.sh` file from the Compose template project
3. Update `shared/build.gradle.kts` file to include ios targets (see template project's `shared` module)
4. Update Decompose library to the `experimental` version (see link above) and make sure that they are added with `api(...)` and not `implementation(...)`
5. Add additional ios libraries and plugins or update existing ones for any library that requires different dependencies for iOS (e.g. essenty) - **This part is hidden across multiple docs**
6. Update `kotlin.framework` exports to include all necessary exports - **This part is hidden in docs**
5. Update `iOSApp.swift` and any other Swift files according to the [Decompose sample](https://github.com/arkivanov/Decompose/tree/compose-experimental/sample) and the Compose template - **This part is tricky**
6. Update the "Compile Sources" in the build phases of `*.xcworkspace` via XCode if swift files were added / removed and not in the list - **This may be in the Gradle or cocoapods plugin docs, otherwise no docs have information about this step**

The above steps represent only brief step-by-step instructions and may not include all the information for successfully running adding iOS support. Swift code examples with Decompose using Compose for making this working would be probably a big help for most of us.

@arkivanov Is there any sample project I have missed where Decompose uses Compose in the iOS module? I could only find [this one](https://github.com/arkivanov/Decompose/tree/compose-experimental/sample/app-ios/app-ios).

But as you can see, there are quite a few steps to execute in order to make things work, plus the fact there there is no single source available yet that explains things in detail in a more abstract level.

**Comment by arkivanov** [comment]
I will think how we could improve the docs. Currently, the idea is to avoid duplicating any other docs as much as possible, e.g. copying code snippets from oficial Kotlin Multiplatform setup guides. This is because they quickly become outdated.

> Is there any sample project I have missed where Decompose uses Compose in the iOS module?

The one you have found is the main Decompose sample with SwiftUI. In that branch, there is also [app-darwin-compose](https://github.com/arkivanov/Decompose/tree/compose-experimental/sample/app-darwin-compose), which uses Compose for iOS. You can also check https://github.com/oianmol/SlackComposeMultiplatform and https://github.com/MohamedRejeb/Pokedex.

As far as I know, there are two ways of integrating Compose for iOS:

1. You can create an `iosApp` Gradle module with `Main.kt` file, so there is no need to create an Xcode project (it gets generated). See the [sample](https://github.com/arkivanov/Decompose/blob/compose-experimental/sample/app-darwin-compose/src/uikitMain/kotlin/com/arkivanov/sample/app/Main.kt).
2. You can create an Xcode project and call integrate Compose from there. See the [sample](https://github.com/JetBrains/compose-multiplatform/blob/a609db563a2014265caec189c615c45213ed66ff/examples/imageviewer/iosApp/iosApp/ContentView.swift#L18).

This makes it even more difficult to describe the setup process. So my approach has been so far as follows:

1. A developer should familiarize themselves with Kotlin Multiplatform, Gradle, Compose Multiplatform, etc.
2. Also familiarize themselves with Kotlin/Native, exporting dependencies, etc.
3. Be able to initialise a dummy project with all required targets and apps (e.g. by cloning the template and running it). 
4. Then with that background, add and export all required Decompose modules

Currently, I intentionally avoid the first 3 steps in Decompose docs, though we could provide some useful links. The 4th step should be pretty easy given the docs (yet I'm happy to improve if needed).

**Comment by devjorgecastro** [comment]
> Yes, this can be challenging. But I feel that this is due to the general steep learning curve with KMP? Assuming you have a project kick-started from e.g. [JetBrains/compose-multiplatform-template](https://github.com/JetBrains/compose-multiplatform-template), would the existing Decompose docs enough?

After spending a couple of hours I managed to make the project work, currently I created a template that I will upload soon to have it as a guide, I checked several repositories that implemented **Decompose** and they were very confusing, I think it would be very helpful to have a very basic template only with the implementation of *Decompose*, what it costs is to do the initial configuration

**Comment by arkivanov** [comment]
Indeed, a template would be useful! Thanks for sharing!

**Comment by arkivanov** [comment]
Another question about templates. How should we cover cases when multiple UI frameworks are possible for a particular platform? E.g. for iOS, one may prefer Compose for iOS or SwiftUI.

One of the ways would be to have two shared Kotlin modules, one for components and another for Compose UI. And have two iOS apps, one for Compose and another for SwiftUI. The user may delete one of them.

**Comment by devjorgecastro** [comment]
> Another question about templates. How should we cover cases when multiple UI frameworks are possible for a particular platform? E.g. for iOS, one may prefer Compose for iOS or SwiftUI.
> 
> One of the ways would be to have two shared Kotlin modules, one for components and another for Compose UI. And have two iOS apps, one for Compose and another for SwiftUI. The user may delete one of them.


I like the idea, it would be good to have templates for different cases; some will prefer native frameworks, while others will use Compose Multiplatform.

**Comment by malliaridis** [comment]
> Another question about templates. How should we cover cases when multiple UI frameworks are possible for a particular platform?

I guess it depends on whether we consider the Compose implementation "shared code" (including iOS) or not. Since there is a module that does not need / use the Compose part (iOS with SwiftUI), the Compose should be a separate module that uses the `shared` module where the Decompose implementation is stored.

And as you mentioned two iOS app modules, one with Compose and one with SwiftUI, would be necessary.

However, from personal experience, having too many gradle modules in the same project has a big impact in IDE performance.

I was also considering smaller templates or a plugin for configuring the project on creation, like IntelliJ provides when creating a new project (see below), but that would probably be too much to maintain.

<img width="796" alt="Screenshot 2023-08-02 at 13 58 58" src="https://github.com/arkivanov/Decompose/assets/33470669/216d2303-f671-4f21-9681-9916c451b395">

**Comment by arkivanov** [comment]
Well, I believe in general the more modules a project has the better for build times. E.g. I successfully worked on an Android project with hundreds of Gradle modules. 

But in our case, this is just a question of +1 Gradle module, e.g. `compose-ui` that depends on `compose`. Shouldn't be a big deal in terms of IDE performance.

**Comment by malliaridis** [comment]
> Well, I believe in general the more modules a project has the better for build times. E.g. I successfully worked on an Android project with hundreds of Gradle modules.

That is an interesting observation. My team and I were having critical performance issues when we were running a project with a couple (less than 10) multiplatform modules. The times of indexing and auto-completion suggestions were taking ages and sometimes stopped working completely. Maybe because it was in a kind-of experimental state back then? I guess I have to play around more with the newer state.

> [...] this is just a question of +1 Gradle module, [...]

You are completely right. This shouldn't be a problem here and is probably the best option, especially in terms of maintainability.

In what way could the template be provided to developers? Maybe something like a template project in Github (like [JetBrain's Compose Multiplatform template](https://github.com/JetBrains/compose-multiplatform-template/))?

**Comment by arkivanov** [comment]
> In what way could the template be provided to developers? Maybe something like a template project in Github

I'm also thinking about a template GitHub repository. Sounds like a good and easy way to kick-start a project. I could create an empty repository by tomorrow so everyone could contribute. Does it sound good?

**Comment by arkivanov** [comment]
Sorry for the delay. Created a repository here: https://github.com/arkivanov/decompose-multiplatform-template

**Comment by arkivanov** [comment]
The template is being discussed here: https://github.com/arkivanov/decompose-multiplatform-template/discussions/1

**Comment by arkivanov** [comment]
The template has been initialized. Closing this for now.

**Comment by arkivanov** [comment]
Added a template link to the readme and quick start docs.
