### ISSUE TITLE
Main thread checks make testing with Coroutines very difficult

### ISSUE THREAD

**Issue by chrisbanes** [arkivanov/Decompose#490]
Decompose contains a number of main thread checks throughout the codebase. Whilst I can understand why these are useful at runtime (although I do think they are very restrictive and presumptuous), they make testing difficult when used alongside Kotlin Coroutines.

A typical Coroutines test would look something like this:

``` kotlin
@Test
fun `test something with decompose`() = runTest {
    val testDispatcher = UnconfinedTestDispatcher(testScheduler)
    Dispatchers.setMain(testDispatcher)

    // Create Decompose component
}
```

Unfortunately you can quickly hit exceptions, such as the following when calling `StackNavigation.push()`:

```
com.arkivanov.decompose.mainthread.NotOnMainThreadException: Expected to be called on the main thread, but was Test worker @kotlinx.coroutines.test runner#2
	at com.arkivanov.decompose.mainthread.CheckMainThreadKt.checkMainThread(CheckMainThread.kt:7)
	at com.arkivanov.decompose.Relay.accept(Relay.kt:20)
	at com.arkivanov.decompose.router.stack.DefaultStackNavigation.navigate(DefaultStackNavigation.kt:11)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push(StackNavigatorExt.kt:16)
	at com.arkivanov.decompose.router.stack.StackNavigatorExtKt.push$default(StackNavigatorExt.kt:15)
```

Can we add a way to disable these checks in tests?

**Comment by arkivanov** [comment]
Thanks for the question. Which platform is this?

**Comment by chrisbanes** [comment]
JVM, but it doesn’t really matter what platform is used as the tests won’t be using the platform Main dispatcher (on purpose).

**Comment by arkivanov** [comment]
I will check, thanks.

**Comment by arkivanov** [comment]
I think I could add an API to disable main thread checks. Though this should be only happening on JVM/Desktop targets with `extensions-compose-jetbrains` module added as a dependency.
On iOS tests are running on the main thread, so as long as you are using only `UnconfinedTestDispatcher` - it should work. 
On Android with JUnit - the checks are disabled because `Looper` is unavailable. Only instrumented tests may be affected, but I would prefer using real dispatchers with instrumented/integration tests.

**Comment by arkivanov** [comment]
I think the reason I didn't catch this earlier in the [TodoApp](todoappDecomposeMviKotlin) sample is because it has a separate `compose-ui` module for Compose UI, and all components with their tests are in separate modules without `extensions-compose-jetbrains`. For the UI we could write simple screenshot tests, but this is another story.
Thanks for raising!

**Comment by arkivanov** [comment]
Btw, I have just realised that you can disable throwing this error as follows:

```kotlin
import com.arkivanov.decompose.errorhandler.onDecomposeError

@Before
fun before {
    onDecomposeError = null
}
```

WDYT? It might be still useful to have a dedicated API for disabling main thread checks.

**Comment by chrisbanes** [comment]
Interesting! `onDecomposeError = null` seems like a good way to disable this.

For now I've just moved over to using Android unit tests instead. We were only really using the JVM target for testing anyway, so this feels like the best target to test on anyway.

**Comment by arkivanov** [comment]
It appears that those exceptions are just logs, they do not fail tests. As [mentioned in the docs](https://arkivanov.github.io/Decompose/navigation/overview/#navigation-and-the-main-thread), the navigation is thread safe, but it's advised to navigate only on the main thread. There are checks that print error logs when access on a non-main thread is detected. 

As suggested, we can use `onDecomposeError = {}` to disable error logs in tests. This can also be used to hook to an analytics/telemetry logging system.

Closing this for now. Feel free to reopen if there are any questions or concerns.

**Comment by arkivanov** [comment]
Btw, the new API for disabling main thread checks has been added recently: https://github.com/arkivanov/Decompose/pull/964
