### ISSUE TITLE
stackAnimation triggers content refresh multiple times

### ISSUE THREAD

**Issue by celcius112** [arkivanov/Decompose#523]
Hi 👋,

Using `stackAnimation`, multiple content refresh are performed when only one is needed. This issue is reproducible in the [decompose template](https://github.com/arkivanov/decompose-multiplatform-template) (see [RootContent](https://github.com/arkivanov/decompose-multiplatform-template/blob/master/compose-ui/src/commonMain/kotlin/com/example/myapplication/root/RootContent.kt#L29)).

Reproduced on a desktop app.

**Comment by arkivanov** [comment]
Could please described what is "multiple content refresh"? If you mean recompositions during animations, then this is expected. This itself shouldn't affect performance, as inner Composable calls should be skipped.

**Comment by celcius112** [comment]
Hi, sorry if I wasn't specific enough, it is my first day using Kotlin Compose (and Decompose) 😁. 

What I basically meant is that I was surprised to see the `content` lambda being called multiple times when an animation is applied. If this is working as intended then so be it, I will try to adapt my workflow knowing that.

**Comment by celcius112** [comment]
Doing some more tests in the template, removing the component argument for `WelcomeContent` makes the component being composed only once : 
```
            when (val instance = it.instance) {
                ...
                is Child.Welcome -> WelcomeContent()
            }
```
While keeping the argument the component will be composed multiple times.

I'll close this since my issue probably comes from my inexperience on the matter

**Comment by celcius112** [comment]
for anyone encountering this issue, it seems like the `ComponentContext` is not immutable. Adding `@Immutable` (from `androidx.compose.runtime.Immutable`) on the component seems to resolve the issue, although I can't be certain this is a good solution.

**Comment by arkivanov** [comment]
Child composables can be recomposed multiple times during transition animations. This is normal as [explained](https://developer.android.com/jetpack/compose/mental-model#recomposition) in Compose docs.

> Composable functions might be re-executed as often as every frame, such as when an animation is being rendered. Composable functions should be fast to avoid jank during animations.

Even though your child composable is recomposed, it shouldn't cause any performance issues. So I wouldn't add any Compose annotations on components, unless there are measurable performance issues that can't be fixed otherwise. Recomposition of the child composable doesn't mean that it gets fully redrawn. Since your child composable content doesn't change, those inner composables will be skipped anyway.
