### ISSUE TITLE
Use adaptive components like ListDetailPaneScaffold in sample code

### ISSUE THREAD

**Issue by rsktash** [arkivanov/Decompose#617]
Multi pane sample code using [ListDetailPaneScaffold](https://developer.android.com/jetpack/compose/layouts/list-detail) (M3)

**Comment by arkivanov** [comment]
Thanks for the proposal. I'm afraid it's technically not possible, because `ListDetailPaneScaffold` is part of the [Material 3 adaptive library](https://developer.android.com/reference/kotlin/androidx/compose/material3/adaptive/package-summary), which is not multiplatform. Also, it relies on some sort of `rememberListDetailPaneScaffoldNavigator`, which looks like a duplication of what Decompose offers.

**Comment by arkivanov** [comment]
Instead, we can rely on [Window Class API](https://developer.android.com/jetpack/compose/layouts/adaptive) and switch modes using Decompose. Part of this API is multiplatform.

**Comment by arkivanov** [comment]
Sorry, I was a bit wrong. The library is Multiplatform, though only Android and Desktop targets are supported. Other points still look valid.

**Comment by rsktash** [comment]
The library became multiplatform. Maybe now it's time to discuss this topic?

**Comment by arkivanov** [comment]
It looks like the scaffold acts as navigation controller (see `rememberListDetailPaneScaffoldNavigator`). Currently, I don't see how it can be used with Decompose, because Decompose is already a navigation controller. The main sample features a multi-pane navigation example. It even adapts dynamically on resize. It could be simplified quite a lot of the dynamic resize is not needed (e.g. you only support Android and iOS).

Feel free to share your ideas if you think ListDetailPaneScaffold could be useful with Decompose. Maybe draft an example of API, or something.

**Comment by arkivanov** [comment]
The latest release [3.2.0-beta01](https://github.com/arkivanov/Decompose/releases/tag/3.2.0-beta02) adds the new Child Panels navigation model (experimental).
