### ISSUE TITLE
Optimize navigation functions for performance

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Decompose#641]
The functions in `StackNavigatorExt` could be improved in the following ways:

1. Mark the rest of the functions inline (only popWhile is inline right now)
2. Use sequences where the number of operations is more than 1 (currently `replaceCurrent`, `pushToFront`)
3. (optionally) Use `is` + reified instead of `this::class == other::class` + sequence for `bringToFront`

**Comment by arkivanov** [comment]
Thanks for raising the issue!

1. Making `StackNavigatorExt` functions `inline` won't improve performance, because `StackNavigator` is an interface and its main method `navigate` accepts normal functions. If we make such a function `inline`, we would have to make arguments `noinline`. 
2. Using sequences won't help. We can't add or remove items from sequence (pushToFront), and `dropLast(1)` from a sequence would still use O(N) memory (in fact, there is no Sequence#dropLast function). Also, since the expected amount of items in the stack is expected to be relatively small, it's better to prefer idiomatic code over micro-optimised.
3. `bringToFront` by design removes configurations by exact class, not by instance check. I've added a test for this case.

**Comment by arkivanov** [comment]
Actually, some of the navigation extensions are already `inline` with `crossinline` lambdas. Let's inline the rest as well.
