### ISSUE TITLE
Navigation animation causes content to not invalidate

### ISSUE THREAD

**Issue by mvarnagiris** [arkivanov/Decompose#655]
We ran into a very weird problem which was very sneaky and took as quite a few days to finally track down. I'll try my best to explain. We have a screen that loads from backend. When that is done we know what components we need to display and we show skeleton versions of those components while real content loads. So basically double loading happens on the screen. We noticed that **sometimes** the skeleton values never go away, even though the content loads. In the end we found that if we have `StackAnimation` set, then this problem can be reproduced. If we set it to `null` then everything works fine.

I created a [sample app](https://github.com/mvarnagiris/DecomposeAnimationBug) where this can be reproduced. It seems like it happens sometimes when the total load time is close to when the screen animation ends. To test it you need to keep on clicking "Restart" button which restarts current screen and everything is reloaded. Once you see the "LOADED!!!" value never go away this is the bug.

We have a temporary fix - wrap those `Composables` with `key(data) { Composable(data) }`

It's a bit complex and if you need any more info let me know. We could even jump on a call if you want to streamline the conversation a bit.

**Comment by arkivanov** [comment]
Thanks for reporting the issue. How do you specify the animation exactly? Can show some code? In the sample you are using `noAnimation`.

**Comment by mvarnagiris** [comment]
Yeah I specifically set it to `noAnimation`. The bug is reproducible with this. Seems like as long as `StackAnimator` is set, the bug can be reproduced - the animation itself does not matter.

**Comment by mvarnagiris** [comment]
To reproduce the bug you might need to tap restart about like 5-10 times. If it does not happen then maybe tweak the first value by increasing it a bit

**Comment by arkivanov** [comment]
Thanks! Is it also reproducible if you specify the animation as follows?

```kotlin
selector = { noAnimation() },
```

Instead of

```kotlin
selector = { _, _, _ -> noAnimation() },
```

**Comment by mvarnagiris** [comment]
Oh interesting. If I do
```kotlin
            animation = stackAnimation(
                disableInputDuringAnimation = true,
                animator = noAnimation(),
            ),
```
Then I cannot reproduce

**Comment by arkivanov** [comment]
Thanks for confirming! There are [three overloads](https://github.com/arkivanov/Decompose/blob/5c8cac89b660441fe11cbd52330dc4a9107ecfce/extensions-compose-jetbrains/src/commonMain/kotlin/com/arkivanov/decompose/extensions/compose/jetbrains/stack/animation/StackAnimation.kt#L33) of the `stackAnimation` animation function. The one with `selector = { child, otherChild, direction -> ... }` is annotated with `@FaultyDecomposeApi` for a reason. Please see the docs for that overload.

I think it's yet another bug in Compose `movableContent` function. There were few other bugs with `movableContent` in the past, but they all were fixed. Could you please also try updating or downgrading the version of Compose and see if it changes anything? If it's not yet fixed in a newer Compose version, then we should create a reproducer with `movableContentOf` but without Decompose (should be pretty easy to do), and report it [here](https://b.corp.google.com/issues/new?component=610764&template=1424126). I might help with the reproducer, let me know.

**Comment by mvarnagiris** [comment]
Ah ok cool I might be able to update our code to not use that `MovableStackAnimation`. Although we do rely on `Direction`. I will try to create a reproduced without decompose. Will ping you if I need help with that. Thanks a lot!

**Comment by arkivanov** [comment]
Thank you!

**Comment by arkivanov** [comment]
I have extracted a reproducer without Decompose and filed [b/327814644](https://issuetracker.google.com/issues/327814644). Closing this issue for now. Thanks again!
