### ISSUE TITLE
Expose more parameters for predictive back animations

### ISSUE THREAD

**Issue by Nek-12** [arkivanov/Decompose#661]
Our team needs the following parameters of the predictive back animation to be exposed:

* exit and enter animation thresholds (from `androidPredictiveBackAnimatable`), others apply too
```kotlin
alpha = 1F - exitProgress
        scaleX = 1F - exitProgress * 0.1F // these magic numbers
        scaleY = scaleX
        translationX = size.width * 0.5F * exitProgress

//

 alpha = totalProgress
        scaleX = lerp(start = 0.95F, stop = 0.90F, fraction = enterProgress).plusFinishProgress(enterFinishProgress)
        scaleY = scaleX
        translationX = lerp(start = -size.width * 0.15F, stop = 0F, fraction = totalProgress)

// 

    private fun Float.exitProgress(): Float =
        if (this < PROGRESS_THRESHOLD) this else 1F

    private fun Float.enterProgress(): Float =
        if (this < PROGRESS_THRESHOLD) {
            0F
        } else {
            1F - 0.6F * (1F - this) / (1F - PROGRESS_THRESHOLD) // magic numbers
        }

    private companion object {
        private const val PROGRESS_THRESHOLD = 0.05F
    }
```
It's a waste to copy and paste the code just to be able to change these numbers. Consider making these magic numbers parameters. A good linter like detekt can help detect (pun not intended) such issues.

**Comment by arkivanov** [comment]
Thanks for the request! I've spent quite some time playing with the API and extracting various arguments, and couldn't discover any good and reasonable API with parameters, that would work nice with different argument values. Also, extracting  those "magic" numbers as public arguments would nail down the implementation details and formulas. In the future there may be a need to change the entire math to something completely different, so that the extract arguments would not make sense.

On the other hand I'm happy to consider any adjustments in the current implementation. Feel free to file a new issue with proposed changes and a video recording of how it looks like.
